package net.sathyan.model;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the DOC_MANG_DOCS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="DOC_MANG_DOCS"
 */
public abstract class BaseDocMangDocs  implements Serializable {

	public static String PROP_DOCUMENT = "document";
	public static String PROP_DOCUMENT_TEMP_HISTORY_ID = "documentTempHistoryId";
	public static String PROP_MANAGER_IS_TRUTHFULLNESS = "managerIsTruthfullness";
	public static String PROP_ASSOCIATE_OFFICE_RECORD = "associateOfficeRecord";
	public static String PROP_IS_CONSENT = "isConsent";
	public static String PROP_DOCUMENT_MASK_ID = "documentMaskId";
	public static String PROP_ASSOCIATE_DOCUMENT_HISTORY = "associateDocumentHistory";
	public static String PROP_CREATED_USER_ID = "createdUserId";
	public static String PROP_SIGNATURE = "signature";
	public static String PROP_DOC_MANG_DOC_ID = "docMangDocId";
	public static String PROP_ASSOCIATE_DOCUMENT = "associateDocument";
	public static String PROP_FILE_NAME = "fileName";
	public static String PROP_MANAGER_SIGNATURE = "managerSignature";
	public static String PROP_CREATED_DATE = "createdDate";
	public static String PROP_MANAGER_IS_CONSENT = "managerIsConsent";
	public static String PROP_LT_FILE_TYPE_ID = "ltFileTypeId";
	public static String PROP_IS_TRUTHFULLNESS = "isTruthfullness";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Long _docMangDocId;
	
	private java.lang.Long _associateDocumentId;

	public java.lang.Long getAssociateDocumentId() {
		return _associateDocumentId;
	}

	public void setAssociateDocumentId(java.lang.Long _associateDocumentId) {
		this._associateDocumentId = _associateDocumentId;
	}


	// fields
	private java.sql.Blob _document;
	private java.lang.String _isConsent;
	private java.lang.String _signature;
	private java.lang.String _isTruthfullness;
	private java.lang.String _managerIsConsent;
	private java.lang.String _managerSignature;
	private java.lang.String _managerIsTruthfullness;
	private java.util.Date _createdDate;
	private java.lang.Long _ltFileTypeId;
	private java.lang.String _fileName;
	private java.lang.Long _createdUserId;
	private java.lang.Long _documentMaskId;
	private java.lang.Long _documentTempHistoryId;

	
	// constructors
	public BaseDocMangDocs () {}

	/**
	 * Constructor for primary key
	 */
	public BaseDocMangDocs (java.lang.Long _docMangDocId) {
		this.setDocMangDocId(_docMangDocId);
	}

	/**
	 * Constructor for required fields
	 */
	public BaseDocMangDocs (
		java.lang.Long _docMangDocId,
		java.util.Date _createdDate,
		java.lang.Long _createdUserId) {

		this.setDocMangDocId(_docMangDocId);
		this.setCreatedDate(_createdDate);
		this.setCreatedUserId(_createdUserId);
	}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="DOC_MANG_DOC_ID"
     */
	public java.lang.Long getDocMangDocId () {
		return _docMangDocId;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _docMangDocId the new ID
	 */
	public void setDocMangDocId (java.lang.Long _docMangDocId) {
		this._docMangDocId = _docMangDocId;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: DOCUMENT
	 */
	public java.sql.Blob getDocument () {
		return _document;
	}

	/**
	 * Set the value related to the column: DOCUMENT
	 * @param _document the DOCUMENT value
	 */
	public void setDocument (java.sql.Blob _document) {
		this._document = _document;
	}


	/**
	 * Return the value associated with the column: IS_CONSENT
	 */
	public java.lang.String getIsConsent () {
		return _isConsent;
	}

	/**
	 * Set the value related to the column: IS_CONSENT
	 * @param _isConsent the IS_CONSENT value
	 */
	public void setIsConsent (java.lang.String _isConsent) {
		this._isConsent = _isConsent;
	}


	/**
	 * Return the value associated with the column: SIGNATURE
	 */
	public java.lang.String getSignature () {
		return _signature;
	}

	/**
	 * Set the value related to the column: SIGNATURE
	 * @param _signature the SIGNATURE value
	 */
	public void setSignature (java.lang.String _signature) {
		this._signature = _signature;
	}


	/**
	 * Return the value associated with the column: IS_TRUTHFULNESS
	 */
	public java.lang.String getIsTruthfullness () {
		return _isTruthfullness;
	}

	/**
	 * Set the value related to the column: IS_TRUTHFULNESS
	 * @param _isTruthfullness the IS_TRUTHFULNESS value
	 */
	public void setIsTruthfullness (java.lang.String _isTruthfullness) {
		this._isTruthfullness = _isTruthfullness;
	}


	/**
	 * Return the value associated with the column: MANAGER_IS_CONSENT
	 */
	public java.lang.String getManagerIsConsent () {
		return _managerIsConsent;
	}

	/**
	 * Set the value related to the column: MANAGER_IS_CONSENT
	 * @param _managerIsConsent the MANAGER_IS_CONSENT value
	 */
	public void setManagerIsConsent (java.lang.String _managerIsConsent) {
		this._managerIsConsent = _managerIsConsent;
	}


	/**
	 * Return the value associated with the column: MANAGER_SIGNATURE
	 */
	public java.lang.String getManagerSignature () {
		return _managerSignature;
	}

	/**
	 * Set the value related to the column: MANAGER_SIGNATURE
	 * @param _managerSignature the MANAGER_SIGNATURE value
	 */
	public void setManagerSignature (java.lang.String _managerSignature) {
		this._managerSignature = _managerSignature;
	}


	/**
	 * Return the value associated with the column: MANAGER_IS_TRUTHFULNESS
	 */
	public java.lang.String getManagerIsTruthfullness () {
		return _managerIsTruthfullness;
	}

	/**
	 * Set the value related to the column: MANAGER_IS_TRUTHFULNESS
	 * @param _managerIsTruthfullness the MANAGER_IS_TRUTHFULNESS value
	 */
	public void setManagerIsTruthfullness (java.lang.String _managerIsTruthfullness) {
		this._managerIsTruthfullness = _managerIsTruthfullness;
	}


	/**
	 * Return the value associated with the column: CREATED_DATE
	 */
	public java.util.Date getCreatedDate () {
		return _createdDate;
	}

	/**
	 * Set the value related to the column: CREATED_DATE
	 * @param _createdDate the CREATED_DATE value
	 */
	public void setCreatedDate (java.util.Date _createdDate) {
		this._createdDate = _createdDate;
	}


	/**
	 * Return the value associated with the column: LT_FILE_TYPE_ID
	 */
	public java.lang.Long getLtFileTypeId () {
		return _ltFileTypeId;
	}

	/**
	 * Set the value related to the column: LT_FILE_TYPE_ID
	 * @param _ltFileTypeId the LT_FILE_TYPE_ID value
	 */
	public void setLtFileTypeId (java.lang.Long _ltFileTypeId) {
		this._ltFileTypeId = _ltFileTypeId;
	}


	/**
	 * Return the value associated with the column: FILE_NAME
	 */
	public java.lang.String getFileName () {
		return _fileName;
	}

	/**
	 * Set the value related to the column: FILE_NAME
	 * @param _fileName the FILE_NAME value
	 */
	public void setFileName (java.lang.String _fileName) {
		this._fileName = _fileName;
	}


	/**
	 * Return the value associated with the column: CREATED_USER_ID
	 */
	public java.lang.Long getCreatedUserId () {
		return _createdUserId;
	}

	/**
	 * Set the value related to the column: CREATED_USER_ID
	 * @param _createdUserId the CREATED_USER_ID value
	 */
	public void setCreatedUserId (java.lang.Long _createdUserId) {
		this._createdUserId = _createdUserId;
	}


	/**
	 * Return the value associated with the column: DOCUMENT_MASK_ID
	 */
	public java.lang.Long getDocumentMaskId () {
		return _documentMaskId;
	}

	/**
	 * Set the value related to the column: DOCUMENT_MASK_ID
	 * @param _documentMaskId the DOCUMENT_MASK_ID value
	 */
	public void setDocumentMaskId (java.lang.Long _documentMaskId) {
		this._documentMaskId = _documentMaskId;
	}


	/**
	 * Return the value associated with the column: DOCUMENT_TEMPLATE_HISTORY_ID
	 */
	public java.lang.Long getDocumentTempHistoryId () {
		return _documentTempHistoryId;
	}

	/**
	 * Set the value related to the column: DOCUMENT_TEMPLATE_HISTORY_ID
	 * @param _documentTempHistoryId the DOCUMENT_TEMPLATE_HISTORY_ID value
	 */
	public void setDocumentTempHistoryId (java.lang.Long _documentTempHistoryId) {
		this._documentTempHistoryId = _documentTempHistoryId;
	}


	

	

	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getDocMangDocId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getDocMangDocId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}