/*
 * Created on 2020-03-13 ( Time 18:07:50 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite)

package net.sathyan.model;

import java.io.Serializable;
import java.math.BigDecimal;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Persistent class for entity stored in table "RT_PTR_ATTENDANCE_BONUS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="RT_PTR_ATTENDANCE_BONUS", schema="PROD" )
// Define named queries here
public class RtPtrAttendanceBonus
    implements Serializable, Cloneable
{

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="RT_PTR_ATTENDANCE_BONUS_ID", nullable=false)
    @SequenceGenerator( name = "RtPtrAttendanceBonussSeq", schema="PROD", sequenceName = "RT_PTR_ATTENDANCE_BONUS_SEQ", allocationSize = 1, initialValue = 1 )
    @GeneratedValue( strategy = GenerationType.SEQUENCE, generator = "RtPtrAttendanceBonussSeq" )
    private Long       rtPtrAttendanceBonusId ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
    @Column(name="SCHED_WEEK_PAYROLL_ID")
    private Long       schedWeekPayrollId ;

    @Column(name="OFFICE_ID")
    private Long       officeId     ;

    @Column(name="IS_MID_WK_TRANSMIT", length=1)
    private String     isMidWkTransmit ;

    @Column(name="MID_WEEK_DATA_ID")
    private Long       midWeekDataId ;

    @Column(name="SCHED_WEEK_ID")
    private Long       schedWeekId  ;

    @Column(name="WEEK_NO")
    private Long       weekNo       ;

    @Column(name="YEAR_NO")
    private Long       yearNo       ;

    @Column(name="HOURS")
    private BigDecimal       hours        ;

    @Column(name="PAY_AMOUNT")
    private BigDecimal       payAmount    ;

    @Column(name="BILL_AMOUNT")
    private BigDecimal       billAmount   ;

    @Column(name="BONUS_PAY_AMOUNT")
    private BigDecimal       bonusPayAmount ;

    @Column(name="BONUS_BILL_AMOUNT")
    private BigDecimal       bonusBillAmount ;

    @Column(name="IS_BONUS", length=1)
    private String     isBonus      ;

    @Column(name="IS_HHC", length=1)
    private String     isHhc        ;

    @Column(name="SHARED_PAYROLL_GROUP_ID")
    private Long       sharedPayrollGroupId ;

    @Column(name="SPG_TRANSMIT_MAPPING_ID")
    private Long       spgTransmitMappingId ;
    
    @Column(name="UNITS")
    private Long       units ;
    
    @Column(name="SCHED_WEEK_PAYROLL_PTR_ID")
    private Long       schedWeekPayrollPtrId ;
    
    @Column(name="DESCRIPTION", length=30)
    private String     description ;
    
    @Column(name="IS_ACA_FLAT_RATE_ENABLED", length=1)
    private String     isAcaFlatRateEnabled  ;
    
    @Column(name="SORT_ORDER")
    private Long       sortOrder     ;


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public RtPtrAttendanceBonus() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setRtPtrAttendanceBonusId( Long rtPtrAttendanceBonusId ) {
        this.rtPtrAttendanceBonusId = rtPtrAttendanceBonusId ;
    }
    public Long getRtPtrAttendanceBonusId() {
        return this.rtPtrAttendanceBonusId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : SCHED_WEEK_PAYROLL_ID ( NUMBER )
    public void setSchedWeekPayrollId( Long schedWeekPayrollId ) {
        this.schedWeekPayrollId = schedWeekPayrollId;
    }
    public Long getSchedWeekPayrollId() {
        return this.schedWeekPayrollId;
    }

    //--- DATABASE MAPPING : OFFICE_ID ( NUMBER )
    public void setOfficeId( Long officeId ) {
        this.officeId = officeId;
    }
    public Long getOfficeId() {
        return this.officeId;
    }

    //--- DATABASE MAPPING : IS_MID_WK_TRANSMIT ( CHAR )
    public void setIsMidWkTransmit( String isMidWkTransmit ) {
        this.isMidWkTransmit = isMidWkTransmit;
    }
    public String getIsMidWkTransmit() {
        return this.isMidWkTransmit;
    }

    //--- DATABASE MAPPING : MID_WEEK_DATA_ID ( NUMBER )
    public void setMidWeekDataId( Long midWeekDataId ) {
        this.midWeekDataId = midWeekDataId;
    }
    public Long getMidWeekDataId() {
        return this.midWeekDataId;
    }

    //--- DATABASE MAPPING : SCHED_WEEK_ID ( NUMBER )
    public void setSchedWeekId( Long schedWeekId ) {
        this.schedWeekId = schedWeekId;
    }
    public Long getSchedWeekId() {
        return this.schedWeekId;
    }

    //--- DATABASE MAPPING : WEEK_NO ( NUMBER )
    public void setWeekNo( Long weekNo ) {
        this.weekNo = weekNo;
    }
    public Long getWeekNo() {
        return this.weekNo;
    }

    //--- DATABASE MAPPING : YEAR_NO ( NUMBER )
    public void setYearNo( Long yearNo ) {
        this.yearNo = yearNo;
    }
    public Long getYearNo() {
        return this.yearNo;
    }

    //--- DATABASE MAPPING : HOURS ( NUMBER )
    public void setHours( BigDecimal hours ) {
        this.hours = hours;
    }
    public BigDecimal getHours() {
        return this.hours;
    }

    //--- DATABASE MAPPING : PAY_AMOUNT ( NUMBER )
    public void setPayAmount( BigDecimal payAmount ) {
        this.payAmount = payAmount;
    }
    public BigDecimal getPayAmount() {
        return this.payAmount;
    }

    //--- DATABASE MAPPING : BILL_AMOUNT ( NUMBER )
    public void setBillAmount( BigDecimal billAmount ) {
        this.billAmount = billAmount;
    }
    public BigDecimal getBillAmount() {
        return this.billAmount;
    }

    //--- DATABASE MAPPING : BONUS_PAY_AMOUNT ( NUMBER )
    public void setBonusPayAmount( BigDecimal bonusPayAmount ) {
        this.bonusPayAmount = bonusPayAmount;
    }
    public BigDecimal getBonusPayAmount() {
        return this.bonusPayAmount;
    }

    //--- DATABASE MAPPING : BONUS_BILL_AMOUNT ( NUMBER )
    public void setBonusBillAmount( BigDecimal bonusBillAmount ) {
        this.bonusBillAmount = bonusBillAmount;
    }
    public BigDecimal getBonusBillAmount() {
        return this.bonusBillAmount;
    }

    //--- DATABASE MAPPING : IS_BONUS ( CHAR )
    public void setIsBonus( String isBonus ) {
        this.isBonus = isBonus;
    }
    public String getIsBonus() {
        return this.isBonus;
    }

    //--- DATABASE MAPPING : IS_HHC ( CHAR )
    public void setIsHhc( String isHhc ) {
        this.isHhc = isHhc;
    }
    public String getIsHhc() {
        return this.isHhc;
    }

    //--- DATABASE MAPPING : SHARED_PAYROLL_GROUP_ID ( NUMBER )
    public void setSharedPayrollGroupId( Long sharedPayrollGroupId ) {
        this.sharedPayrollGroupId = sharedPayrollGroupId;
    }
    public Long getSharedPayrollGroupId() {
        return this.sharedPayrollGroupId;
    }

    //--- DATABASE MAPPING : SPG_TRANSMIT_MAPPING_ID ( NUMBER )
    public void setSpgTransmitMappingId( Long spgTransmitMappingId ) {
        this.spgTransmitMappingId = spgTransmitMappingId;
    }
    public Long getSpgTransmitMappingId() {
        return this.spgTransmitMappingId;
    }
    
    //--- DATABASE MAPPING : UNITS ( NUMBER )
    public void setUnits( Long units ) {
        this.units = units;
    }
    public Long getUnits() {
        return this.units;
    }
    
    //--- DATABASE MAPPING : SCHED_WEEK_PAYROLL_PTR_ID ( NUMBER )
    public void setSchedWeekPayrollPtrId( Long schedWeekPayrollPtrId ) {
        this.schedWeekPayrollPtrId = schedWeekPayrollPtrId;
    }
    public Long getSchedWeekPayrollPtrId() {
        return this.schedWeekPayrollPtrId;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR2 )
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }
    
    //--- DATABASE MAPPING : IS_ACA_FLAT_RATE_ENABLED ( CHAR )
    public void setIsAcaFlatRateEnabled( String isAcaFlatRateEnabled ) {
        this.isAcaFlatRateEnabled = isAcaFlatRateEnabled;
    }
    public String getIsAcaFlatRateEnabled() {
        return this.isAcaFlatRateEnabled;
    }
    
  //--- DATABASE MAPPING : SORT_ORDER ( NUMBER )
    public void setSortOrder( Long sortOrder ) {
        this.sortOrder = sortOrder;
    }
    public Long getSortOrder() {
        return this.sortOrder;
    }
    
    

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(rtPtrAttendanceBonusId);
        sb.append("]:"); 
        sb.append(schedWeekPayrollId);
        sb.append("|");
        sb.append(officeId);
        sb.append("|");
        sb.append(isMidWkTransmit);
        sb.append("|");
        sb.append(midWeekDataId);
        sb.append("|");
        sb.append(schedWeekId);
        sb.append("|");
        sb.append(weekNo);
        sb.append("|");
        sb.append(yearNo);
        sb.append("|");
        sb.append(hours);
        sb.append("|");
        sb.append(payAmount);
        sb.append("|");
        sb.append(billAmount);
        sb.append("|");
        sb.append(bonusPayAmount);
        sb.append("|");
        sb.append(bonusBillAmount);
        sb.append("|");
        sb.append(isBonus);
        sb.append("|");
        sb.append(isHhc);
        sb.append("|");
        sb.append(sharedPayrollGroupId);
        sb.append("|");
        sb.append(spgTransmitMappingId);
        sb.append("|");
        sb.append(units);
        sb.append("|");
        sb.append(schedWeekPayrollPtrId);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append("isAcaFlatRateEnabled");
        sb.append("|");
        sb.append("sortOrder");
        return sb.toString(); 
    } 



    //----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
    public RtPtrAttendanceBonus clone()
        throws CloneNotSupportedException
    {
        RtPtrAttendanceBonus clone = (RtPtrAttendanceBonus)super.clone();

        return clone;
    }
}
