/*
 * Created on 2020-11-20 ( Time 14:21:32 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
// This Bean has a basic Primary Key (not composite)

package model.valueobjects;
import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

/**
 * Persistent class for entity stored in table "OFFICE_TRAINING_CONFIGS"
 *
 * @author Telosys Tools Generator
 *
 */


// Define named queries here
public class OfficeTrainingConfigs
    implements Serializable, Cloneable
{

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
      private Long       officeTrainingConfigId ;

  private Long       officeId     ;

    private String     code         ;

   private String     description  ;

    private Long       ltTrainingEntityTypeId ;

    private String     isActive     ;

    private Long       createdBy    ;

    private Date       createdDate  ;

    private Long       updatedBy    ;

      private Date       updatedDate  ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OfficeTrainingConfigs() {
        super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOfficeTrainingConfigId( Long officeTrainingConfigId ) {
        this.officeTrainingConfigId = officeTrainingConfigId ;
    }
    public Long getOfficeTrainingConfigId() {
        return this.officeTrainingConfigId;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : OFFICE_ID ( NUMBER )
    public void setOfficeId( Long officeId ) {
        this.officeId = officeId;
    }
    public Long getOfficeId() {
        return this.officeId;
    }

    //--- DATABASE MAPPING : CODE ( CHAR )
    public void setCode( String code ) {
        this.code = code;
    }
    public String getCode() {
        return this.code;
    }

    //--- DATABASE MAPPING : DESCRIPTION ( VARCHAR2 )
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : LT_TRAINING_ENTITY_TYPE_ID ( NUMBER )
    public void setLtTrainingEntityTypeId( Long ltTrainingEntityTypeId ) {
        this.ltTrainingEntityTypeId = ltTrainingEntityTypeId;
    }
    public Long getLtTrainingEntityTypeId() {
        return this.ltTrainingEntityTypeId;
    }

    //--- DATABASE MAPPING : IS_ACTIVE ( CHAR )
    public void setIsActive( String isActive ) {
        this.isActive = isActive;
    }
    public String getIsActive() {
        return this.isActive;
    }

    //--- DATABASE MAPPING : CREATED_BY ( NUMBER )
    public void setCreatedBy( Long createdBy ) {
        this.createdBy = createdBy;
    }
    public Long getCreatedBy() {
        return this.createdBy;
    }

    //--- DATABASE MAPPING : CREATED_DATE ( DATE )
    public void setCreatedDate( Date createdDate ) {
        this.createdDate = createdDate;
    }
    public Date getCreatedDate() {
        return this.createdDate;
    }

    //--- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy( Long updatedBy ) {
        this.updatedBy = updatedBy;
    }
    public Long getUpdatedBy() {
        return this.updatedBy;
    }

    //--- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate( Date updatedDate ) {
        this.updatedDate = updatedDate;
    }
    public Date getUpdatedDate() {
        return this.updatedDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(officeTrainingConfigId);
        sb.append("]:"); 
        sb.append(officeId);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(ltTrainingEntityTypeId);
        sb.append("|");
        sb.append(isActive);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(createdDate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        return sb.toString(); 
    } 



    //----------------------------------------------------------------------
    // clone METHOD
    //----------------------------------------------------------------------
    public OfficeTrainingConfigs clone()
        throws CloneNotSupportedException
    {
        OfficeTrainingConfigs clone = (OfficeTrainingConfigs)super.clone();

        return clone;
    }
}
